export const PRODUCT_LIST_FETCHING = "PRODUCT_LIST_FETCHING";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";

export const FILTER_DATA = "FILTER_DATA";
export const RESET_FILTER_DATA = "RESET_FILTER_DATA";

export const LOGIN_USER = "LOGIN_USER";
